// COMMON ACTION TYPES
// LOGIN
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

// AUTHENTICATE_USER
export const AUTHENTICATE_USER = "AUTHENTICATE_USER";

// SIGNUP
export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";

// LOGOUT
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

// PROFILE
export const PROFILE_START = "PROFILE_START";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_FAILED = "PROFILE_FAILED";

// UPDATE PROFILE
export const UPDATE_PROFILE_START = "UPDATE_PROFILE_START";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";

// GET PRODUCTS
export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

// //

// USER ACTION TYPES
// GET CART
export const GET_CART_START = "GET_CART_START";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILED = "GET_CART_FAILED";

// GET ORDER
export const GET_ORDER_START = "GET_ORDER_START";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILED = "GET_ORDER_FAILED";

// GET SAVED PRODUCTS
export const GET_SAVED_PRODUCTS_START = "GET_SAVED_PRODUCTS_START";
export const GET_SAVED_PRODUCTS_SUCCESS = "GET_SAVED_PRODUCTS_SUCCESS";
export const GET_SAVED_PRODUCTS_FAILED = "GET_SAVED_PRODUCTS_FAILED";

export const TOGGLE_PRODUCT_CART_START = "TOGGLE_PRODUCT_CART_START";
// REMOVE PRODUCT TO CART
export const DELETE_PRODUCT_CART_SUCCESS = "DELETE_PRODUCT_CART_SUCCESS";
// ADD PRODUCT TO CART
export const ADD_PRODUCT_CART_SUCCESS = "ADD_PRODUCT_CART_SUCCESS";
export const TOGGLE_PRODUCT_CART_FAILED = "TOGGLE_PRODUCT_CART_FAILED";

// BUY PRODUCT
export const BUY_PRODUCT_START = "BUY_PRODUCT_START";
export const BUY_PRODUCT_SUCCESS = "BUY_PRODUCT_SUCCESS";
export const BUY_PRODUCT_FAILED = "BUY_PRODUCT_FAILED";

// RATE PRODUCT
export const RATE_PRODUCT_START = "RATE_PRODUCT_START";
export const RATE_PRODUCT_SUCCESS = "RATE_PRODUCT_SUCCESS";
export const RATE_PRODUCT_FAILED = "RATE_PRODUCT_FAILED";

// SAVE PRODUCT
export const SAVE_PRODUCT_START = "SAVE_PRODUCT_START";
export const SAVE_PRODUCT_SUCCESS = "SAVE_PRODUCT_SUCCESS";
export const SAVE_PRODUCT_FAILED = "SAVE_PRODUCT_FAILED";

// //

// SELLER ACTION TYPES
// ADD PRODUCT
export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

// DELETE PRODUCT
export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const OUTOFSTOCK_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";
